[package]
name = "didc"
version = "0.3.5"
authors = ["DFINITY Team"]
edition = "2021"

[dependencies]
candid = { path = "../../rust/candid", features = ["all"] }
candid_parser = { path = "../../rust/candid_parser", features = ["all"] }
clap = { version = "4.3", features = ["derive"] }
pretty-hex = "0.2.1"
hex = "0.4.2"
anyhow = "1.0.32"
rand = "0.8"
